apiVersion: v1
kind: Service
metadata:
  name: python-ecg-service
  namespace: python-ecg
  labels:
    app: ecg-ia-python
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ecg-ia-python
