name: Docker Build and Push

on:
  push:
    branches: [ "devops", "main" ]
  workflow_dispatch:
  
env:
  REGISTRY: crretoxmas2024.azurecr.io
  IMAGE_NAME: python-ia-ecg

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # Build y push de la imagen
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  #facu
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Kubernetes
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=kubeconfig

    - name: Restart Kubernetes deployment
      run: |
        export KUBECONFIG=kubeconfig
        kubectl apply -k k8s/
        kubectl rollout restart deployment python-ecg-deployment -n python-ecg